version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-13.18
    working_directory: /home/stackage
    environment:
      CPATH: /usr/include/hdf5/serial
      LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/hdf5/serial
    steps:
      - checkout
      - run: |
          sudo apt update &&
          sudo apt -y install libhdf5-dev hdf5-tools
      - restore_cache:
          key: cache-lts-13.18
      - run: |
          stack --no-terminal --system-ghc build --haddock --test --only-dependencies
      - save_cache:
          key: cache-lts-13.18
          paths:
            - ~/.stack
      - run: |
          stack --no-terminal --system-ghc build --haddock --test --no-run-tests
          stack --no-terminal --system-ghc run hdf5-hs
          stack --no-terminal --system-ghc install
